# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BigMoneyShot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BigMoneyShot
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  pod 'GoogleSignIn'
  
  pod 'FacebookCore'
  pod 'FacebookLogin'
  
  pod 'Stripe'
  
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.5'
  
  pod 'SwiftyJSON', '~> 4.0'
  
  pod 'CodableFirebase'
  # Swift 3
  # Extended beyond UITextField
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
  

end
